# Makefile for running/testing code

# use this target enter an interactive python shell using the virtual python
ipython:
	PYTHONPATH=. ../virtual_python/bin/ipython

# start the program with the main method in zircons_rock_terminal.py
zircons_rock:
	PYTHONPATH=. ../virtual_python/bin/python ./zircons_rock_terminal.py
