# Makefile for running/testing code

# use this target enter an interactive python shell using the virtual python
ipython:
	PYTHONPATH=. ../virtual_python/bin/ipython

# start the main method in main.py
main:
	PYTHONPATH=. ../virtual_python/bin/python ./main.py
